blank_issues_enabled: false
contact_links:
	name: Get help on the Discord Server
	url: https://discord.gg/SN89y7EQTN
	about: If your issue doesn't match any of the above templates, join our discord and ask about it there.
